<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{__('Sales Performance Report')}}</title>
    <style>
        body { font-family: sans-serif; font-size: 9px; } /* Slightly smaller font for more data */
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 5px; text-align: left; } /* Slightly less padding */
        th { background-color: #f2f2f2; }
        .total-row td { font-weight: bold; }
        .report-header { text-align: center; margin-bottom: 15px; }
        .report-header h1 { font-size: 16px; margin-bottom: 5px; }
        .report-details { margin-bottom: 15px; }
        .report-details p { margin: 1px 0; }
        .text-right { text-align: right; }
    </style>
</head>
<body>
    <div class="report-header">
        <h1>{{__('Sales Performance Report')}}</h1>
        <p>{{__('Generated on')}}: {{ \Carbon\Carbon::now()->format('d/m/Y H:i:s') }}</p>
        <p>{{__('Generated by')}}: {{ auth()->user()->name }}</p>
    </div>

    <div class="report-details">
        <p><strong>{{__('Date Range')}}:</strong> {{ $dateRangeFilterName }}</p>
        <p><strong>{{__('Seller')}}:</strong> {{ $sellerFilterName }}</p>
        @if(!empty($searchQuery))
        <p><strong>{{__('Search')}}:</strong> "{{ $searchQuery }}"</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>{{__('Bill ID')}}</th>
                <th>{{__('Code')}}</th>
                <th>{{__('Date')}}</th>
                <th>{{__('Client')}}</th>
                <th>{{__('Seller')}}</th>
                <th>{{__('Status')}}</th>
                <th class="text-right">{{__('Net Amount')}} ($)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($bills as $bill)
                <tr>
                    <td>{{ $bill->id }}</td>
                    <td>{{ $bill->code ?? 'N/A' }}</td>
                    <td>{{ (new Carbon($bill->created_at))->format('d/m/Y H:i:s') }}</td>
                    <td>{{ $bill->client_name ?? 'N/A' }}</td>
                    <td>{{ $bill->seller_name ?? 'N/A' }}</td>
                    <td>{{ $bill->status ?? 'N/A' }}</td>
                    <td class="text-right">{{ number_format($bill->net_amount ?? 0, 2, '.', ',') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">{{__('No sales found for the selected filters.')}}</td>
                </tr>
            @endforelse
            <tr class="total-row">
                <td colspan="6" style="text-align: right;"><strong>{{__('GRAND TOTAL')}}:</strong></td>
                <td class="text-right"><strong>{{ number_format($grandTotalAmount ?? 0, 2, '.', ',') }}</strong></td>
            </tr>
        </tbody>
    </table>
</body>
</html>